### ISSUE TITLE
RuntimeError after 1 epoch

### ISSUE THREAD

**Issue by valeriydutt** [kekmodel/FixMatch-pytorch#26]
```
01/14/2021 19:40:10 - INFO - models.wideresnet -   Model: WideResNet 28x2
01/14/2021 19:40:10 - INFO - __main__ -   Total params: 1.47M
01/14/2021 19:40:19 - INFO - __main__ -   ***** Running training *****
01/14/2021 19:40:19 - INFO - __main__ -     Task = cifar10@4000
01/14/2021 19:40:19 - INFO - __main__ -     Num Epochs = 1024
01/14/2021 19:40:19 - INFO - __main__ -     Batch size per GPU = 64
01/14/2021 19:40:19 - INFO - __main__ -     Total train batch size = 64
01/14/2021 19:40:19 - INFO - __main__ -     Total optimization steps = 1048576
Train Epoch: 1/1024. Iter: 1024/1024. LR: 0.0300. Data: 0.253s. Batch: 0.569s. Loss: 1.2500. Loss_x: 1.2062. Loss_u: 0.0437. Mask: 0.08. : 100% 1024/1024 [09:42<00:00,  1.76it/s]
  0% 0/157 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 475, in <module>
    main()
  File "train.py", line 291, in main
    model, optimizer, ema_model, scheduler, writer)
  File "train.py", line 393, in train
    test_loss, test_acc = test(args, test_loader, test_model, epoch)
  File "train.py", line 450, in test
    prec1, prec5 = accuracy(outputs, targets, topk=(1, 5))
  File "/content/FixMatch-pytorch/utils/misc.py", line 41, in accuracy
    correct_k = correct[:k].view(-1).float().sum(0)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
  0% 0/157 [00:01<?, ?it/s]
  ```

Any help is appreciated!

**Comment by kekmodel** [comment]
You can change `view(-1)` to `reshape(-1)`.

**Comment by valeriydutt** [comment]
Thank you very much!
